In [1]:
import numpy as np
import random
def loss(X, y, w, lr):
    dummy=np.array(y.shape)
    x=np.concatenate((dummy,X),axis=0)
    return x

In [9]:
X=np.random.randn(100,5)
# print(X)
y=np.random.randn(100,1)
# print(y)
w=np.random.randn(6,1)
print(X.shape, y.shape)

(100, 5) (100, 1)


In [12]:
a=np.ones(y.shape)
x=np.concatenate((a,X),axis=1)
lr=3

In [13]:
ridge=(1/2)*(np.transpose(x@w-y)@(x@w-y))+(lr/2)*(np.transpose(w)@w)

In [14]:
ridge

array([[570.4500102]])

In [17]:
def x_transform(X, degrees):
    
    # X --> Input.
    # degrees --> A list, We add X^(value) feature to the input
    #             where value is one of the values in the list.
    
    # making a copy of X.
    t = X.copy()
    
    # Appending columns of higher degrees to X.
    for i in range(degrees):
        X = np.append(X, t**i, axis=1)
            
    return X

In [21]:
a=np.random.randn(5,1)
b=x_transform(a,2)
print(a)

[[-0.77467237]
 [-2.5742028 ]
 [ 0.55665859]
 [-1.06551276]
 [-1.95780429]]


In [22]:
print(b)

[[-0.77467237  1.         -0.77467237]
 [-2.5742028   1.         -2.5742028 ]
 [ 0.55665859  1.          0.55665859]
 [-1.06551276  1.         -1.06551276]
 [-1.95780429  1.         -1.95780429]]


In [23]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)
poly.fit_transform(a)

array([[ 1.        , -0.77467237,  0.60011728],
       [ 1.        , -2.5742028 ,  6.62652008],
       [ 1.        ,  0.55665859,  0.30986878],
       [ 1.        , -1.06551276,  1.13531743],
       [ 1.        , -1.95780429,  3.83299764]])

In [26]:
def transform( degree, X ) :
  m,n=X.shape
  X_transform = np.ones( ( m, 1 ) )
  j = 0 
  for j in range(degree + 1 ) :
    if j != 0 :
      x_pow = np.power( X, j )
      X_transform = np.append( X_transform, x_pow.reshape( -1, 1 ), axis = 1 )
  return X_transform 

In [27]:
transform(2,a)

array([[ 1.        , -0.77467237,  0.60011728],
       [ 1.        , -2.5742028 ,  6.62652008],
       [ 1.        ,  0.55665859,  0.30986878],
       [ 1.        , -1.06551276,  1.13531743],
       [ 1.        , -1.95780429,  3.83299764]])