In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [ ]:
X,y=load_breast_cancer(return_X_y=True)

In [ ]:
X.shape

(569, 30)

In [ ]:
np.unique(y)

array([0, 1])

In [ ]:
count=0
for i in range(len(y)):
  if y[i]==0:
    count=count+1
count

212

In [ ]:
data = load_breast_cancer(as_frame=True)
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

In [ ]:
import seaborn as sns

In [ ]:
cancer = load_breast_cancer()
df_features = pd.DataFrame(cancer.data, columns = cancer.feature_names)
df_target = pd.DataFrame(cancer.target, columns=['target'])
df = pd.concat([df_features, df_target], axis=1)

In [ ]:
# As discussed above, some dependent variables in the dataset might be highly correlated with each other. Let's explore the correlation of three examples above.

def correlation(var):
    """
    1. Print correlation
    2. Create jointplot
    """
    # Print correlation
    print("Correlation: ", df[[var[0], var[1]]].corr().iloc[1, 0])

In [ ]:
correlation(['mean perimeter' ,'mean radius'])

Correlation:  0.9978552814938109


In [ ]:
from sklearn.impute import SimpleImputer
a=np.array([[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]])
s=SimpleImputer()
b=s.fit_transform(a)

In [ ]:
b

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [ ]:
from sklearn.preprocessing import FunctionTransformer
f=FunctionTransformer(np.log10)
a=f.fit_transform(np.array( [[1, 1], [2, 3],[10,100]]))

In [ ]:
a

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])

In [ ]:
# head=['class1','class2','class3']
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df1=df[0]
df2=df[1]
df3=df[2]
df4=df[3]

In [ ]:
frames=[df1,df2,df3,df4]
features=pd.concat(frames,axis=1)

In [ ]:
features

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
p=PolynomialFeatures(2)
a=p.fit_transform(features)

In [ ]:
a

array([[ 1.  ,  5.1 ,  3.5 , ...,  1.96,  0.28,  0.04],
       [ 1.  ,  4.9 ,  3.  , ...,  1.96,  0.28,  0.04],
       [ 1.  ,  4.7 ,  3.2 , ...,  1.69,  0.26,  0.04],
       ...,
       [ 1.  ,  6.5 ,  3.  , ..., 27.04, 10.4 ,  4.  ],
       [ 1.  ,  6.2 ,  3.4 , ..., 29.16, 12.42,  5.29],
       [ 1.  ,  5.9 ,  3.  , ..., 26.01,  9.18,  3.24]])

In [ ]:
a.shape

(150, 15)

In [1]:
import numpy as np
import pandas as pd

In [6]:
class LinearReg(object):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  
  def predict(self,x,w):
    return np.transpose(self.x)@w
  def  loss(self,x,y,w):
    e=self.predict(x,w)-y
    return 0.5*np.transpose(e)@e

In [22]:
x=np.array([[1,2],[3,4]])
y=np.array([[2],[1]])
ls=LinearReg(x,y)
ls.predict(x,y)


array([[5],
       [8]])

In [10]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()
l.fit(x,y)

LinearRegression()

In [12]:
l.predict(x)

array([[2.],
       [1.]])

In [16]:
def mse(ypred,y):
  n=len(y)
  return (1/n)*np.sum(np.sqrt(np.square(ypred)-np.square(y)))

In [20]:
y=np.array([[1],[3]])
ypred=np.array([[1],[1]])
np.sqrt(np.square(ypred)-np.square(y))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 0.],
       [nan]])

In [23]:
x.ndim

2

In [24]:
import itertools
import functools

In [26]:

def poly(x,degree):
  if x.ndim==1:
    x=x[:,None]
  xt=np.transpose(x)
  features=[np.ones(len(x))]
  for degree in range(1,degree+1):
    for items in itertools.combinations_with_replacement(xt,degree):
      features.append(functools.reduce(lambda x,y:x*y , items))
  return np.asarray(features).transpose()


In [27]:
poly(x,2)

array([[ 1.,  1.,  2.,  1.,  2.,  4.],
       [ 1.,  3.,  4.,  9., 12., 16.]])

In [34]:
def poly(x,degree):
  if x.ndim==1:
    x=x[:,None]
  xt=np.transpose(x)
  features=[np.ones(len(x))]
  for degree in range(1,degree+1):
    for items in itertools.combinations_with_replacement(xt,degree):
      features.append(functools.reduce(lambda x , y:x*y, items))
  return np.asarray(features).transpose()


In [35]:
poly(y,3)

array([[1., 2., 4., 8.],
       [1., 1., 1., 1.]])

In [42]:
def perpred(x,w):
  z=x@w
  return np.sum(np.where(z>0,1,0))

In [43]:
perpred(np.array([[1,2],[3,1]]),np.array([[1],[-2]]))

1

In [53]:
def perploss(y,ypred):
  e=np.max(0,-ypred*y)
  return np.sum(e)

In [54]:
perploss(np.array([[1,1,0]]),np.array([[0,1,1]]))

TypeError: ignored

In [55]:
def graddis(x,y,lr,ep):
  for i in np.arange(0,ep):
    djdw=np.transpose(x)@(x@w-y)
    w=w-lr*djdw
  return w

In [61]:
def PolynomialFeatures(x,degree):
  if x.ndim==1:
    x=x[:,None]
  xt=np.transpose(x)
  features=[np.ones(len(x))]
  for degree in range(1,degree+1):
    for items in itertools.combinations_with_replacement(xt,degree):
      features.append(functools.reduce(lambda x, y:x*y,items))
  return np.asarray(features).transpose()

In [62]:
y=np.array([[1],[3]])
PolynomialFeatures(y,4)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  3.,  9., 27., 81.]])

In [63]:
def loss(x,y,w,lr):
  base=0.5*(np.tranpose(x)@w-y)
  ridge=base+(lr/2)*np.transpose(w)@w
  lasso=base+(lr/2)*np.sum(np.abs(w))
  if ridge<lasso:
    return ridge
  else:
    return lasso

In [64]:
def add_dum(X):
  m,n=X.shape
  one=np.ones((m,1))
  return np.concatenate((one,X),axis=1)

In [65]:
add_dum(y)

array([[1., 1.],
       [1., 3.]])

In [66]:
from sklearn.datasets import fetch_california_housing
X,y=fetch_california_housing(return_X_y=True)

In [73]:
from sklearn.feature_selection import SelectPercentile
Xnew=SelectPercentile(percentile=10).fit_transform(X,y)

In [74]:
Xnew.shape

(20640, 1)

In [75]:
X.shape

(20640, 8)

In [ ]:
from sklearn