# **DS 1**

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.preprocessing import Normalizer
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [2]:
data=pd.read_csv('/content/data_for_large_scale.csv')
random_state=10

FileNotFoundError: ignored

In [ ]:
data.columns
features=['Feature-1', 'Feature-2', 'Feature-3', 'Feature-4', 'Feature-5',
          'Feature-6', 'Feature-7', 'Feature-8', 'Feature-9', 'Feature-10']
data.describe()

In [ ]:
X=data[features]
y=data.Target
X.head(),y.head()

In [ ]:
X_array, y_array = X.to_numpy(), y.to_numpy()
X_array, y_array

In [ ]:
train_X, test_X, train_y, test_y = train_test_split(X_array, y_array, test_size=0.3, random_state=random_state)

In [ ]:
train_X.shape, test_X.shape

In [ ]:
train_y.shape, test_y.shape

In [ ]:
train_X, test_X, train_y, test_y = train_X.reshape((-1,90,10)), test_X.reshape((-1,90,10)), train_y.reshape((-1,90)), test_y.reshape((-1,90))

In [ ]:
train_X.shape, test_X.shape, train_y.shape, test_y.shape

In [ ]:
len(train_X)

In [ ]:
sgd = SGDRegressor(random_state=random_state)
c=[]
for i in range(len(train_X)):
  px = train_X[i]
  py = train_y[i]
  sgd.partial_fit(px,py)
  c.append(sgd.coef_)

In [ ]:
sgd.intercept_

In [ ]:
sgd.coef_.round(2)

In [ ]:
test_X, test_y = test_X.reshape((27000,10)), test_y.reshape((27000,))

In [ ]:
test_y.shape, test_X.shape

In [ ]:
y_pred = sgd.predict(test_X)
y_pred

In [ ]:
c[4][4].round(2)

In [ ]:
r2_score(test_y, y_pred)

# **DS 3**

In [ ]:
iris_X, iris_y = load_iris(return_X_y=True)
iris_X, iris_y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [ ]:
train_iris_X, test_iris_X, train_iris_y, test_iris_y = train_test_split(iris_X, iris_y,test_size=0.2, random_state = random_state)
train_iris_X.shape, test_iris_X.shape, train_iris_y.shape, test_iris_y.shape

((120, 4), (30, 4), (120,), (30,))

In [ ]:
tr, ts = Normalizer().fit_transform(train_iris_X), Normalizer().fit_transform(test_iris_X)
tr[:5], ts[:5]

(array([[0.76301853, 0.33526572, 0.53180079, 0.15029153],
        [0.75728103, 0.3542121 , 0.52521104, 0.15878473],
        [0.73089855, 0.30454106, 0.58877939, 0.1624219 ],
        [0.67767924, 0.32715549, 0.59589036, 0.28041899],
        [0.72965359, 0.28954508, 0.57909015, 0.22005426]]),
 array([[0.77530021, 0.28304611, 0.54147951, 0.15998258],
        [0.71576546, 0.30196356, 0.59274328, 0.21249287],
        [0.80373519, 0.55070744, 0.22325977, 0.02976797],
        [0.73260391, 0.36029701, 0.55245541, 0.1681386 ],
        [0.81228363, 0.5361072 , 0.22743942, 0.03249135]]))

In [ ]:
for i in [2,3,4]:
  knn=KNeighborsClassifier(n_neighbors=i)
  knn.fit(tr, train_iris_y)
  p = knn.predict(ts)
  print(i,classification_report(test_iris_y, p, output_dict=True)['accuracy'])
  print(i,f1_score(test_iris_y,p, average='weighted').round(2))


2 0.9666666666666667
2 0.97
3 0.9666666666666667
3 0.97
4 0.9666666666666667
4 0.97


# **DS 2**

In [38]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt",
               chunksize=20000, iterator =True,header=None)
df

In [39]:
full_data = pd.concat(df, ignore_index=True)

In [40]:
features=[1,2]
X=full_data[features]
X=X.to_numpy()
y=y.to_numpy()
y=full_data[3]
print(X)
print(y)

[[ 9.3498486 56.7408757]
 [ 9.3501884 56.7406785]
 [ 9.3505485 56.7405445]
 ...
 [ 9.9350095 57.4992821]
 [ 9.9434787 57.495919 ]
 [ 9.9434512 57.49627  ]]
0         17.052772
1         17.614840
2         18.083536
3         18.279465
4         18.422974
            ...    
434869    20.134033
434870    20.580884
434871    19.733141
434872    24.027015
434873    24.635285
Name: 3, Length: 434874, dtype: float64


In [41]:
full_data

0         1          2          3
0       144552912  9.349849  56.740876  17.052772
1       144552912  9.350188  56.740679  17.614840
2       144552912  9.350549  56.740544  18.083536
3       144552912  9.350806  56.740485  18.279465
4       144552912  9.351053  56.740486  18.422974
...           ...       ...        ...        ...
434869   93323205  9.936479  57.499686  20.134033
434870   93323205  9.935696  57.499426  20.580884
434871   93323205  9.935009  57.499282  19.733141
434872   93323209  9.943479  57.495919  24.027015
434873   93323209  9.943451  57.496270  24.635285

[434874 rows x 4 columns]

In [42]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434874 entries, 0 to 434873
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   0       434874 non-null  int64  
 1   1       434874 non-null  float64
 2   2       434874 non-null  float64
 3   3       434874 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 13.3 MB


In [43]:
fd=full_data.to_numpy()
# full_data.type
fd

array([[1.44552912e+08, 9.34984860e+00, 5.67408757e+01, 1.70527716e+01],
       [1.44552912e+08, 9.35018840e+00, 5.67406785e+01, 1.76148402e+01],
       [1.44552912e+08, 9.35054850e+00, 5.67405445e+01, 1.80835356e+01],
       ...,
       [9.33232050e+07, 9.93500950e+00, 5.74992821e+01, 1.97331406e+01],
       [9.33232090e+07, 9.94347870e+00, 5.74959190e+01, 2.40270150e+01],
       [9.33232090e+07, 9.94345120e+00, 5.74962700e+01, 2.46352848e+01]])

In [44]:
# sgd = SGDRegressor(random_state=random_state)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.partial_fit(X,y)

StandardScaler()

In [45]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y)

In [46]:
xtrain

array([[ 9.9090484, 57.0428708],
       [ 8.4345176, 56.9022744],
       [10.291405 , 56.6446507],
       ...,
       [10.3374198, 57.0116369],
       [ 8.1792069, 56.6633043],
       [10.005927 , 57.5054484]])

In [47]:
len(xtrain)

326155

In [48]:
xtrain=xtrain.reshape(-1,7,2)
ytrain=ytrain.reshape(-1,7)


ValueError: ignored

In [32]:
sgd = SGDRegressor(random_state=10)
c=[]
for i in range(len(xtrain)):
  px = xtrain[i]
  py = ytrain[i]
  sgd.partial_fit(px,py)
  c.append(sgd.coef_)

In [36]:
c

[array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.06611027]),
 array([-6810907.2018553 , 29917257.0661

In [ ]:
sgd = SGDRegressor(random_state=10)
c=[]
for i in range(len(train_X)):
  px = train_X[i]
  py = train_y[i]
  sgd.partial_fit(px,py)
  c.append(sgd.coef_)

TypeError: ignored