In [4]:
import numpy as np 
import pandas as pd
import itertools
import functools

In [3]:
def get_combinations(x,degree):
  return itertools.combinations_with_replacement(x,degree)

In [6]:
def compute_new(items):
  return functools.reduce(lambda x,y:x*y,items)

In [11]:
def polynomial_features(x,degree):
  if x.ndim==1:
    x=x[:,None]
  xt=np.transpose(x)
  f=[np.ones(len(x))]
  for degree in range(1,degree+1):
    for items in get_combinations(xt,degree):
      f.append(compute_new(items))
  return np.asarray(f).transpose()

In [13]:
polynomial_features(np.array([1,2,3]),2)

array([[1., 1., 1.],
       [1., 2., 4.],
       [1., 3., 9.]])

In [22]:
def binarylabel(x):
  u=np.sort(np.unique(x))
  m,n=x.shape
  trans=np.zeros((m,len(u)))
  k=[]
  for i in x:
    a=np.where(i==u)
    k.append(a)
  return k

In [23]:
binarylabel(np.array([[1,0,2]]))

[(array([2]),)]

In [25]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
l.fit_transform(np.array([1,0,2]))

array([1, 0, 2])

In [26]:
from sklearn.preprocessing import LabelBinarizer
l=LabelBinarizer()
l.fit_transform(np.array([1,0,2]))

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [35]:
from sklearn.preprocessing import OneHotEncoder
o=OneHotEncoder()
o.fit_transform([['Male', 1], ['Female', 3], ['Female', 2]]).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

ValueError: ignored